# Generated by Django 3.2.3 on 2022-02-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skill',
        ),
        migrations.AddField(
            model_name='skills',
            name='skill',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
