# Generated by Django 3.2.3 on 2022-02-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20220221_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True),
        ),
    ]
