# Generated by Django 3.2.3 on 2022-02-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20220224_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(default='default.jpg', upload_to='project_pics'),
        ),
    ]
